language: elixir
dist: xenial

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11

services:
- elasticsearch

env:
  global:
  - PGPORT=5433
  - TEST_DATABASE_PORT=5433
  - TEST_DATABASE_USER=postgres
  - TEST_DATABASE_PASS=

elixir: '1.8'

before_install:
- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.0.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.0.1-amd64.deb && sudo service elasticsearch restart

install:
- sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/11/main/pg_hba.conf
- sudo systemctl restart postgresql@11-main

before_script:
- sleep 10

script:
- mix local.hex --force
- mix local.rebar --force
- mix deps.get
- mix format --check-formatted
- MIX_ENV=test mix ecto.create
- MIX_ENV=test mix ecto.migrate
- MIX_ENV=test mix elasticsearch.build entries --cluster Ptolemy.ElasticsearchCluster
- mix test

notifications:
  email:
    on_success: never
