name: Elixir CI

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: "22.0.7"
        elixir-version: "1.9.1"
    - name: mix release
      run: |
        mix deps.get
        mix deps.compile
        npm install --prefix assets
        npm run --prefix assets deploy
        mix phx.digest
        mix compile
        mix release --path tequila-master
      env:
        MIX_ENV: prod
    - uses: actions/upload-artifact@master
      with:
        name: tequila-master
        path: ./tequila-master
